Alteração de layout (botões do footer e tamanho do modal)
solfacil/components-ui pull request #107
Opened 2021-11-26 18:58 UTC by cakeno

# Descrição

Descrição do que é esperado deste PR

## Stories relacionadas (clubhouse)

- [sc-9425]

## Pontos para atenção

- Mudar os botões do footer do modal para o lado direito (mobile e desktop).
- Mudar o tamanho dos modais apenas na versão mobile, como no handoff.
- Footer com altura fixa;

2021-11-29 18:02 UTC, fernandorjesus approved these changes

2021-12-08 19:18 UTC, costafsk requested changes

2021-12-08 19:18 UTC, costafsk commented on src/assets/scss/_modal.scss
> +      height: auto;
Opa, acho que rola de usar a classe do tailwind `h-auto`

2021-12-08 19:22 UTC, cakeno commented on src/assets/scss/_modal.scss
> +      height: auto;
feito

2021-12-08 19:27 UTC, costafsk approved these changes

2021-12-08 19:45 UTC, merged