Feature/add filter component
solfacil/components-ui pull request #127
Opened 2022-02-09 11:42 UTC by brenodouglas

# Descrição
Este PR visa adicionar o componente de filtro que será usado em outros projetos já com tudo que foi definido pela equipe de design. Foi adicionado também o comando de pré-commit adotado no template de frontend, também foi adicionado um plugin do babel em ambiente de dev que já era sugestão em vários e vários warnings gerados ao rodar o storybook.

## Stories relacionadas (clubhouse)

- [sc-11962](https://app.shortcut.com/solfacil/story/11962/implementar-componente-de-filtro-na-lib-de-ui)

## Pontos para atenção

- Listar pontos para atenção no review
- Listar pontos para atenção nos testes

## Possui novas configurações?

## Screenshots
- Desktop
![Components _ UI Elements _ FilterComponent - Default ⋅ Storybook - desktop](https://user-images.githubusercontent.com/3895280/153193158-a197b04e-1532-4451-ab6a-dbc7f09c57f4.gif)

- Mobile
![MobileComponents _ UI Elements _ FilterComponent - Default ⋅ Storybook (1)](https://user-images.githubusercontent.com/3895280/153193298-f08cdd96-201e-4943-b802-c677418974ce.gif)

2022-02-10 14:05 UTC, lucasalbuquerque requested changes

2022-02-10 14:05 UTC, lucasalbuquerque commented on src/components/FilterComponent/FilterSelectList/FilterSelectList.vue
> +    this.interval = setInterval(() => {
o que acha de criar uma função nomeada e passar para o set interval como callback aqui?

acho válido quando tem muita coisa dentro do set interval

o que acha?

2022-02-10 14:05 UTC, lucasalbuquerque commented on src/components/FilterComponent/FilterSelectList/FilterSelectList.vue
> +    deselectItem(item) {
talvez o correto seja 
```suggestion
    unselectItem(item) {
```

https://www.quora.com/What-is-the-difference-between-Unselect-or-Deselect#:~:text=The%20difference%20between%20deselect%20and,mark%20from%20a%20tick%20box.

2022-02-10 14:58 UTC, brenodouglas commented on src/components/FilterComponent/FilterComponent.vue
> +      for (const item in this.binaryStates) {
Eu conheço o `fill`, porém, nesse caso o binaryStates é um objeto. Mas como vi que tem o lodash no projeto consegui melhorar isso usando o `mapValues`. https://github.com/solfacil/components-ui/pull/127/commits/d0e993819e099e6f1d95e4131fe1f694f198528b

2022-02-10 14:59 UTC, brenodouglas commented on src/components/FilterComponent/FilterComponent.vue
> +    if (filtersForActive && filtersForActive.length > 0) {
https://github.com/solfacil/components-ui/pull/127/commits/d0e993819e099e6f1d95e4131fe1f694f198528b

2022-02-10 15:05 UTC, brenodouglas commented on src/components/FilterComponent/FilterSelectList/FilterSelectList.vue
> +    this.interval = setInterval(() => {
https://github.com/solfacil/components-ui/pull/127/commits/d0e993819e099e6f1d95e4131fe1f694f198528b

2022-02-10 15:05 UTC, brenodouglas commented on src/components/FilterComponent/FilterComponent.vue
> +      switch (filter.type) {
https://github.com/solfacil/components-ui/pull/127/commits/d0e993819e099e6f1d95e4131fe1f694f198528b

2022-02-10 15:05 UTC, brenodouglas commented on src/components/FilterComponent/FilterComponent.vue
> +        switch (filter.type) {
Nesse caso eu usei o `result` do lodash por conta do valor do binary ser `false` acabava dando ruim utilizando essa abordagem.

2022-02-10 15:06 UTC, brenodouglas commented on src/components/FilterComponent/FilterComponent.vue
> +      switch (item.type) {
https://github.com/solfacil/components-ui/pull/127/commits/d0e993819e099e6f1d95e4131fe1f694f198528b

2022-02-10 15:06 UTC, brenodouglas commented on src/components/FilterComponent/FilterComponent.vue
> +    if (filtersForActive && filtersForActive.length > 0) {
https://github.com/solfacil/components-ui/pull/127/commits/d0e993819e099e6f1d95e4131fe1f694f198528b

2022-02-10 15:06 UTC, lucasalbuquerque commented on src/components/FilterComponent/FilterComponent.vue
> +      for (const item in this.binaryStates) {
boa @brenodouglas, tu é o cara!

2022-02-10 15:10 UTC, brenodouglas commented on src/components/FilterComponent/FilterComponent.vue
> +            <template v-if="item.type === 'binary'">
https://github.com/solfacil/components-ui/pull/127/commits/fa077e5a61cc0faf27469de5d78fb1ca4715f65f essa do binary eu preferi centralizar em um metodo e utilizar sempre esse metodo. Acabou que passou batido, mas é uma abordagem que sempre tento adotar.

2022-02-10 15:59 UTC, lucasalbuquerque commented on src/components/FilterComponent/FilterComponent.vue
> +            <template v-if="item.type === 'binary'">
Entendi, de qualquer forma nós estamos usando a string dentro dos métodos itemIsSelected - handleClickMenuItem. 

Acredito ser útil mover para uma constante quando é utilizado mais de uma vez. Mas podemos conversar mais sobre isso em conjunto com o time.

2022-02-10 20:20 UTC, lucasalbuquerque approved these changes

2022-02-17 20:02 UTC, lucasalbuquerque approved these changes

2022-02-17 20:24 UTC, merged