checkbox
solfacil/components-ui pull request #6
Opened 2021-03-30 15:26 UTC by accuvit

# Descrição

Cria a checkbox de acordo com as especificações do figma

## Stories relacionadas (clubhouse)

- [ch-xxx]

2021-03-30 15:27 UTC, accuvit commented
![image](https://user-images.githubusercontent.com/19792530/113014730-3906eb80-9153-11eb-8785-c9130347964c.png)

2021-03-30 15:27 UTC, accuvit commented
![image](https://user-images.githubusercontent.com/19792530/113014776-4328ea00-9153-11eb-933f-8348702644f8.png)

2021-03-31 15:39 UTC, fernandorjesus approved these changes

2021-03-31 15:39 UTC, fernandorjesus commented on src/components/Checkbox/Checkbox.vue
> +      required: false,
Podemos remover se temos um default

2021-03-31 15:39 UTC, fernandorjesus commented on src/components/Checkbox/Checkbox.vue
> +      required: false,
podemos remover se temos um default

2021-03-31 15:39 UTC, fernandorjesus commented on src/components/Checkbox/Checkbox.vue
> +      required: false,
Podemos remover se remos um default

2021-03-31 15:39 UTC, fernandorjesus commented on src/components/Checkbox/Checkbox.vue
> +    errorMsg: {
Faltou documentar a props

2021-03-31 15:39 UTC, fernandorjesus commented on src/components/Checkbox/Checkbox.vue
> +    text: {
Faltou documentar a props

2021-03-31 15:39 UTC, fernandorjesus commented on src/components/Checkbox/Checkbox.vue
> +    label: {
Faltou documentar a props

2021-03-31 15:39 UTC, fernandorjesus commented on src/components/Checkbox/Checkbox.vue
> +      required: false,
Podemos remover se temos um default

2021-03-31 15:39 UTC, fernandorjesus commented
Peguei um erro no responsivo
![image](https://user-images.githubusercontent.com/1573665/113171722-24dbf080-921e-11eb-82b0-c3e815d94581.png)

2021-03-31 15:40 UTC, fernandorjesus commented
Temos mais um erro no console

![Uploading image.png…]()

2021-03-31 15:42 UTC, fernandorjesus requested changes
Temos alguns items para rever

2021-04-01 00:20 UTC, fernandorjesus requested changes

2021-04-01 00:20 UTC, fernandorjesus commented on src/assets/img/icon/icon-check.vue
> +</script>
Porque criamos um componente para um svg?

Podemos importar diretamente a imagem no próprio componente!

2021-04-01 00:20 UTC, fernandorjesus commented on src/components/Checkbox/Checkbox.vue
> +import checkmark from '@/assets/img/icon/icon-check.vue';
Porque temos um componente para um svg?

2021-04-01 00:58 UTC, accuvit commented on src/assets/img/icon/icon-check.vue
> +</script>
As maneiras que eu tentei importar o svg não estavam dando certo (era isso que gerava o erro do console anterior), aí eu acabei fazendo desse jeito. É uma técnica bem utilizada em react também, aí resolvi trazer pra esse repo. Se você achar que não fica legal, podemos fazer uma call e tentar importar o svg de outro jeito.

2021-04-08 17:43 UTC, fernandorjesus commented on src/assets/img/icon/icon-check.vue
> +</script>
Bom conforme falamos no Vue seguimos de outra forma.

2021-04-08 17:44 UTC, fernandorjesus requested changes
Faltou o readme

2021-04-08 20:19 UTC, fernandorjesus approved these changes

2021-04-08 20:19 UTC, merged