Feat/show password
solfacil/components-ui pull request #60
Opened 2021-08-16 21:23 UTC by R-romero

# Descrição

Adiciona ao component Input a possibilidade de dar Show/Hide no content de Inputs tipo Password.

## Stories relacionadas (clubhouse)

- [ch-5930]

## Pontos para atenção

- A implementacão é feita através de uma prop específica chamada controlVisibility, em juncão com o type do input libera acesso aos botões de show/hide;

- Cobertura 100% de acordo com o Jest

## Possui novas configurações?

- N/A

## Possui migrations?

- N/A

2021-08-16 21:52 UTC, alfsouza708 submitted a review, later dismissed

2021-08-17 13:38 UTC, fernandorjesus requested changes

2021-08-17 13:38 UTC, fernandorjesus commented on package.json
> +    "@solfacil/components-ui": "^1.12.0",
Não temos a necessidade deste import aqui

2021-08-17 13:48 UTC, fernandorjesus requested changes
Ao meu ver podemos remover todos os atributos **data-testid** e fazer a busca por classe ou pelo próprio elemento

2021-08-17 13:48 UTC, fernandorjesus commented on src/components/Input/Input.vue
> +          data-testid="search_clear_icon"
Creio que não existe a necessidade de data para teste, podemos usar a classe

2021-08-17 13:48 UTC, fernandorjesus commented on src/components/Input/Input.vue
> +      </slot>
O que esta sendo passado neste slot?

2021-08-17 13:48 UTC, fernandorjesus commented on src/components/Input/Input.vue
> +      <slot v-if="inputType === 'search'">
O que está sendo passado neste slot?

2021-08-17 13:48 UTC, fernandorjesus commented on src/components/Input/Input.unit.spec.js
> +    const clearIcon = wrapper.find('[data-testid="search_clear_icon"]');
Podemos usar a classe .find('.classe')

2021-08-17 13:48 UTC, fernandorjesus commented on src/components/Input/Input.vue
> +        data-testid="input"
Podemos dar um find por: .find('input')

2021-08-17 19:06 UTC, R-romero commented
> Ao meu ver podemos remover todos os atributos **data-testid** e fazer a busca por classe ou pelo próprio elemento

Existem vantagens de se utilizar o data-testid em curto e longo prazo.

 - Facilita na construção de testes E2E e snapshots, já pensando num futuro onde faremos a cobertura;
 - Não morfa a utilidade de classes CSS para além de seu escopo, fazendo uso de uma propriedade não ambigua para a identificação em testes;
 - Garante maior integridade dos testes na necessidade de uma refatoração, diminui os casos de "adicionei uma div e quebrei 15 tests que agora navegam pra um blank spot no DOM ou não encontram a classe esperada"
 
 O unico "downside¨ é que o id fica no DOM de producão, mas a informação em si não tem valor nenhum.
 
 Acho um tema legal de levarmos para as reuniões de frontend.

2021-08-17 22:57 UTC, fernandorjesus commented
> > Ao meu ver podemos remover todos os atributos **data-testid** e fazer a busca por classe ou pelo próprio elemento
> 
> Existem vantagens de se utilizar o data-testid em curto e longo prazo.
> 
> * Facilita na construção de testes E2E e snapshots, já pensando num futuro onde faremos a cobertura;
> * Não morfa a utilidade de classes CSS para além de seu escopo, fazendo uso de uma propriedade não ambigua para a identificação em testes;
> * Garante maior integridade dos testes na necessidade de uma refatoração, diminui os casos de "adicionei uma div e quebrei 15 tests que agora navegam pra um blank spot no DOM ou não encontram a classe esperada"
> 
> O unico "downside¨ é que o id fica no DOM de producão, mas a informação em si não tem valor nenhum.
> 
> Acho um tema legal de levarmos para as reuniões de frontend.
> 
> Alguns links que abordam o assunto:
> https://kentcdodds.com/blog/making-your-ui-tests-resilient-to-change#whats-with-the-data-testid-query
> https://testing-library.com/docs/dom-testing-library/faq/ - I really don't like data-testids, but none of the other queries make sense. Do I have to use a data-testid?

Normalmente este atributo não é utilizado com a biblioteca de[ testes do Vue](https://vue-test-utils.vuejs.org/), por oferece outras opções de acesso ao elemento.

Mas faz sentido, podemos seguir com este formato! 

Quanto a testes E2E, não usaremos este atributo! Como pode ver temos em todos os componente o ID como props obrigatória para atender ao pessoal de QA com testes E2E

O downside me incomoda um pouco :)

2021-08-18 21:28 UTC, R-romero commented on src/components/Input/Input.vue
> +      </slot>
Foi má implementacão da minha parte, substitui por uma div simples.
Optei pelas divs como parent dos 2 conjuntos de icones pra evitar repeticão nas condicões do v-if, seguindo a metodologia DRY.

2021-08-18 21:30 UTC, R-romero commented
Por questões abordadas no dia a dia e a necessidade aparente em outros testes optamos por manter os data-testid em código.

2021-08-20 14:48 UTC, fernandorjesus approved these changes

2021-08-20 15:29 UTC, merged